
discord:
  token: ''
  chat-prefix: ''
  guild-id: 0
  log-channel: 0
  audit-log-channel: 0
  rules-channel: 0
  announce-channel: 0
  reports-channel: 0
  suggestions-channel: 0
  mute-role: 0
  voice-mute-role: 0
  command-prefix: 'ob!'

trello:
  enabled: true
  API-key: ''
  API-token: ''
  # THE ID OF THE LISTS
  issues:
  suggestions:

sql:
  host: ''
  port: 3306
  username: ''
  password: ''
  database: ''
  prefix: 'dmc_'