main: com.github.zaphx.discordbot.Dizcord
name: Dizcord
version: ${project.version}
load: STARTUP
authors: [Zaphoo, Mobkinz78]
api-version: 1.13

commands:
  dizcord:
    usage: /<command> link <code>
  todiscord:
    usage: /<command> <channel> <message>


permissions:
  dizcord.mc:
    default: op
    description: The base in game permission
  dizcord.admin:
    default: op
    description: The default admin permission