main: com.github.zaphx.discordbot.Dizcord
name: DiscordMC2.0
version: 2.0.1
load: STARTUP
authors: [Zaphoo, Mobkinz78]

commands:
  dmc:
    usage: /<command> login|logout
    aliases: [discordmc, dismc]

permissions:
  discord.mc:
    default: op
    description: The base in game permission